icon-project/icon-service

- iconservice/icon_service_engine.py
- tests/test_icon_score_trace.py
- tests/test_icon_service_engine.py
_flag and _icon_score_loader fields were removed
> Cleanup IconServiceEngine

- iconservice/iconscore/icon_score_context_util.py
- tests/test_icon_score_step.py
Refactoring _get_icon_score method in icon_score_context_util
> Refactoring _get_icon_score method in icon_score_context_util

- iconservice/deploy/icon_score_deploy_engine.py
- iconservice/icon_constant.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- tests/integrate_test/test_integrate_import_whitelist.py
- tests/integrate_test/test_integrate_scores.py
- tests/integrate_test/test_integrate_service_configuration.py
- tests/test_icon_service_engine.py
Rewrite the names of constants in EnableThreadFlag and IconServiceFlag class according to PEP8 (#19)
class EnableThreadFlag(IntFlag)
Invoke => INVOKE 
Query => QUERY 
Validate => VALIDATE
class IconServiceFlag(IntFlag)
fee => FEE 
audit => AUDIT 
deployerWhiteList => DEPLOYER_WHITELIST 
scorePackageValidator => SCORE_PACKAGE_VALIDATOR
> Rewrite the names of constants in all capital letters with underscores separating words

- iconservice/database/db.py
* Made function descriptions more clearly
* Fixed some typos
> Cleanup iconservice/database/db.py

- iconservice/iconscore/icon_score_base.py
Fix a wrong msg.sender assignment in IconScoreBase.deploy()
> Fix context.msg.sender bug in IconScoreBase.deploy().

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_step.py
- iconservice/precommit_data_manager.py
- tests/integrate_test/test_integrate_scores.py
- tests/mock_generator.py
- tests/test_icon_score_step.py
- tests/test_icon_service_engine.py
- Puts `theading.lock` into `IconScoreStepFactory` 
- Reduce setting of the STEP properties(step price, step costs, max step limit) to `IconScoreStepFactory`
- IconScoreStepCounter holds copies of STEP properties in a context
> Improve managing Step counter factory

- docs/score-guide/score-by-example.rst
- iconservice/icon_service_engine.py
- tests/integrate_test/test_samples/test_fallback_call_scores/test_link_score_send_A/test_link_score_send.py
- tests/integrate_test/test_samples/test_fallback_call_scores/test_link_score_send_B/test_link_score_send.py
- tests/sample/sample_crowd_sale/sample_crowd_sale.py
if you want to divide integer, must use // not /
> fix wrong int division logic

- iconservice/iconscore/icon_container_db.py
- tests/icon_score/test_icon_container_db.py
- tests/integrate_test/test_integrate_import_whitelist.py
add validator set_item property like get_item property.
> Add negative index processing in ArrayDB setitem

- iconservice/iconscore/score_package_validator.py
- tests/integrate_test/test_integrate_import_whitelist.py
- tests/integrate_test/test_integrate_scores.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule/subpackage/sub_module.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule/subpackage/sub_module2.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule/test_score.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule_method/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule_method/subpackage/sub_module.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule_method/subpackage/sub_module2.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_indirect_submodule_method/test_score.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_submodule/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_submodule/subpackage/sub_module.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/as_test/test_in_submodule/test_score.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin/json/__init__.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin/json/encoder/encoder.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin/test_score.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin2/json/encoder/encoder.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin2/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_builtin2/test_score.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_multiply/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_multiply/test_score.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_multiply/transaction/transaction.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_normal/json/__init__.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_normal/json/encoder/encoder.py
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_normal/package.json
- tests/integrate_test/test_samples/test_deploy_scores/import_test/import_normal/test_score.py
modify import validator logic.
previous logic
compare import string.
improve logic
check relation reference depth.
https://docs.python.org/3/library/dis.html
Changed in version 3.6: Use 2 bytes for each instruction. Previously the number of bytes varied by instruction.
> IS-337: Improve package validator v2

- iconservice/iconscore/icon_container_db.py
- iconservice/utils/__init__.py
* Refactor the key encoding function for future enhancement
* Remove the duplicate codes
* Sync with the py-executor codes
> IS-381: Refactor ContainerDB

- iconservice/__init__.py
- iconservice/iconscore/icon_score_base2.py
- tests/integrate_test/test_samples/test_score_api/test_score_base/test_score_base.py
- tests/test_icon_score_api.py
Add recover_key() and create_address_with_key() to SCORE api.
> IS-373: implement recover_key() and create_address_with_key()

- iconservice/icon_service_cli.py
See the internal JIRA comment.
> IS-385: Refactor the logic that gets the running processes

- iconservice/deploy/icon_score_deploy_engine.py
- iconservice/iconscore/icon_score_api_generator.py
- iconservice/iconscore/icon_score_base.py
- tests/integrate_test/test_integrate_score_oninstall_parameters.py
- tests/integrate_test/test_integrate_scores.py
- tests/integrate_test/test_samples/test_deploy_scores/install/test_legacy_kwargs_params/package.json
- tests/integrate_test/test_samples/test_deploy_scores/install/test_legacy_kwargs_params/test_score.py
IS_369 re fix
move logic score meta class to deploy engine
> IS-410: Improve deploy parameters checking

- iconservice/base/msgpack_util.py
- iconservice/base/type_converter_templates.py
- requirements.txt
- tests/base/test_type_converter_iiss.py
add msgpack util
add template in TypeConverter for IISS
> IS-387 Design IISS DB Data Struct

- iconservice/iconscore/icon_score_base2.py
Remove keword arguments from json_dumps() and json_loads()
> IS-434 remove kwargs from json funcs

- iconservice/icon_config.py
- iconservice/icon_service_engine.py
- iconservice/iiss/database/iiss_batch.py
- iconservice/iiss/database/iiss_db.py
- iconservice/iiss/iiss_data_storage.py
- iconservice/iiss/iiss_engine.py
- iconservice/iiss/reward_calc_proxy.py
- iconservice/utils/__init__.py
- tests/integrate_test/__init__.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_existent_scores.py
- tests/integrate_test/test_integrate_existent_scores_audit.py
- tests/mock_generator.py
- tests/test_icon_service_engine.py
branch icx, iiss on send_tx, query
add iiss_engine
> IS-421: add IISS flow in iconservice engine

- iconservice/iiss/iiss_data_creator.py
- iconservice/iiss/iiss_msg_data.py
- tests/iiss/test_iiss_data_using_level_db.py
Modify iiss data structure (synced to RC)
- Modify Governance Variable
- Add BlockProduceInformation
- Modify P-Rep
> IS-446: Modify iiss data structure

- iconservice/fee/deposit.py
- iconservice/fee/fee_engine.py
- iconservice/fee/score_deposit_info.py
- tests/fee/test_fee_storage.py
- tests/fee/test_score_deposit_info.py
- tests/integrate_test/test_integrate_fee_sharing.py
- tests/test_fee_engine.py
1. Modifies how to calculate the amount that should remain on the deposit
- AS-IS : 500 * 10 ** 18
- TO-BE : 10 percent of the amount of a deposit 
2. Adds version property on Deposit and  ScoreDepositInfo
> Is 447 modify how to calculate remaining deposit

- iconservice/base/address.py
- iconservice/base/type_converter_templates.py
- iconservice/icon_constant.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/icx/icx_engine.py
- iconservice/iiss/__init__.py
- iconservice/iiss/icx_issue_formula.py
- iconservice/iiss/iiss_msg_data.py
- iconservice/iiss/rc_data_storage.py
- iconservice/precommit_data_manager.py
- tests/base/test_type_converter.py
- tests/icx/test_icx_engine.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_iiss.py
- tests/integrate_test/test_integrate_issue_transaction_validation.py
- tests/mock_generator.py
- tests/test_icon_service_engine.py
1. implement ICX issue logic
- implement new protocol (get_issue_info): this method is for loop chain to getting information from the icon service to make issue transaction
- implement issue transaction validation logic
2. implement logic about getting validators and generator from the loopchain
> IS-424: Implement ICX issue logic

- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_inner_service.py
- iconservice/iiss/commit_delegator.py
- iconservice/prep/prep_candidate_container.py
- iconservice/prep/prep_candidate_engine.py
- iconservice/prep/prep_candidate_linked_list.py
- tests/integrate_test/test_integrate_iiss.py
- tests/mock_generator.py
fix minor fix ( typo, merge fix, etc..)
> IS-461: edit save PRep RC data logic

- iconservice/iconscore/icon_container_db.py
fix mismatch type hint.
add comment about type K, V
> Fix the type hint mismatch

- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_result.py
- tests/integrate_test/test_integrate_base.py
- tests/test_icon_score_result.py
- tests/test_icon_service_engine.py
- Add block hash member variable for backward compatibility
- Fix the minor bug
> Rollback TX result data structure

- iconservice/iconscore/icon_score_context.py
- iconservice/icx/icx_engine.py
- tests/icx/test_icx_engine.py
- Remove the total supply member variable and related code in the icx engine
- Add total supply property to the context
> IS-527: Return total supply from the state db when querying

- iconservice/iiss/engine.py
- iconservice/iiss/ipc/reward_calc_proxy.py
- iconservice/iiss/ipc/server.py
- start & stop the reward calculator when open & close the reward calculator proxy
- fixed a runtime warning occurs when closing a reward calculator proxy
> IS-510: Reward calculator lifecycle management

- iconservice/base/type_converter_templates.py
- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/prep/data/prep.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- tests/base/test_type_converter_iiss.py
- tests/integrate_test/iiss/test_iiss_prep_candidate.py
- tests/integrate_test/prep/test_prep.py
- tests/integrate_test/test_integrate_iiss.py
update json rpc api
rename : incentive_rep -> irep
term includes main + sub preps
> IS-567: update json rpc api

- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/inner_call/__init__.py
- write call method in inner_service
> [IS-509]Add MQ message

- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message_queue.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- Add CalculateResponse to notify message handler
- Now can process CalculateResponse generated during RC initialization
> IS-560: Fix notify message handler

- iconservice/database/db.py
* Implement IconScoreSubDatabase
* Fix incorrect step calculation result caused by wrong IconScoreBase.__init__() call order.
> IS-573: Fix db sync failure caused by SCORE

- iconservice/deploy/icon_score_deploy_engine.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_class_loader.py
- iconservice/iconscore/icon_score_mapper_object.py
- tests/integrate_test/test_integrate_deploy_install.py
- tests/integrate_test/test_samples/test_deploy_scores/install/test_score/test_score.py
replace builtin print method to mocking method
> hotfix-1.3.2

- iconservice/deploy/engine.py
- iconservice/deploy/icon_builtin_score_loader.py
- tests/__init__.py
- tests/icon_score/test_icon_score_deploy_storage.py
- tests/icx/test_icx_engine.py
- tests/iiss/ipc/test_message_unpacker.py
- tests/mock_generator.py
- tests/test_fee_engine.py
- tests/test_fee_sharing.py
- tests/test_icon_score_class_loader.py
- tests/test_icon_score_deploy_engine.py
- tests/test_icon_score_deployer.py
- tests/test_icon_score_event.py
- tests/test_icon_score_mapper.py
- tests/test_icon_score_result.py
- tests/test_icon_score_step.py
- tests/test_icon_score_trace.py
- tests/test_icon_zip_deploy.py
- tests/test_system_call_handler.py
Fix context error in unit-tests
> [Is-568] fix context error in unittest

- iconservice/prep/engine.py
- tests/integrate_test/prep/test_prep.py
> IS-544: advanced get prep list method

- iconservice/iiss/__init__.py
- tests/integrate_test/iiss/test_integrate_decentralization_trigger.py
- tests/integrate_test/prep/test_prep.py
Fix getting minimum delegation for bottom prep function.
> IS-514:Implement decentralization trigger

- iconservice/inner_call/__init__.py
- iconservice/prep/engine.py
Add a message that Loopchain querying status of ICON service
> Is-509: add mq message

- iconservice/base/block.py
- iconservice/deploy/storage.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/inner_call/__init__.py
move reward calc logic to invoke
> IS-580: move-reward-calc-logic-to-invoke

- iconservice/icon_service_engine.py
- iconservice/icx/issue/regulator.py
- iconservice/iiss/engine.py
- iconservice/iiss/storage.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- tests/integrate_test/prep/test_preps2.py
- Renames next block height to end block height
- Adds integration-test for it
> IS-578: Sync Calc and Term Period

- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/storage.py
- iconservice/precommit_data_manager.py
- tests/iiss/test_reward_calc_data_storage.py
- tests/integrate_test/test_integrate_issue_transaction_validation.py
- Add version data when recording i score which came from the RC as a response of 'CALCULATE'
While in the period, this data format could be changed. So add version info
- Fix integrate tests about issue transaction
- Modify period check logic
> IS-558: Refactoring issue transaction related logic

- iconservice/icon_service_engine.py
- iconservice/icx/delegation_part.py
- iconservice/iiss/__init__.py
- iconservice/iiss/engine.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/data/sorted_list.py
- iconservice/prep/engine.py
- tests/integrate_test/__init__.py
- tests/integrate_test/prep/test_prep.py
- tests/integrate_test/prep/test_preps.py
- tests/integrate_test/prep/test_preps2.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_iiss.py
- tests/integrate_test/test_integrate_issue_transaction_validation.py
- tests/prep/data/test_prep_container.py
- tests/prep/data/test_sorted_list.py
* Fix integration_test errors except for one test
* Fix errors on tests/prep unittests
* Fix the incorrect usages of PRepContainer
* Make SortedList more robust
> IS-582: Implement IISSEngineListener

- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/prep/data/prep.py
- iconservice/prep/engine.py
- tests/integrate_test/prep/test_preps2.py
* irep can be set only once in term
* irep set 37,500 when register prep
> Is-579: add constraint irep update

- iconservice/icon_service_engine.py
- add 'nextCalculation'
- add 'nextPRepTerm'
> IS-587: Modify IISS debug API

- iconservice/iiss/engine.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- tests/integrate_test/test_integrate_iiss.py
* Optimize PRepContainer.set_delegated_to_prep()
* Rename some variable names for better readability
> IS-589: Refactor IISSEngine.handle_set_delegation

- iconservice/icx/icx_account.py
- iconservice/icx/stake_part.py
- tests/integrate_test/iiss/test_iiss_stake.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_existent_scores.py
- tests/integrate_test/test_integrate_existent_scores_audit.py
- tests/integrate_test/test_integrate_fee_sharing.py
- tests/integrate_test/test_integrate_iiss.py
> IS-599: Fix stake bug

- tests/icon_score/test_icon_pre_validator.py
- tests/iiss/ipc/test_message_unpacker.py
- tests/iiss/test_iiss_data_using_level_db.py
- tests/test_icon_service_engine.py
Modify tests that fail due to parameter changes in methods/functions
> Is-568: fix unittests

- iconservice/icon_inner_service.py
support old loopchain txResult prototal by using is editable.
>  IS-601: Support old loopchain prototal

- iconservice/iiss/engine.py
- tests/integrate_test/iiss/prevote/test_iiss_stake.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/iiss/test_iiss_base.py
bug fix about "we must not stake all amount from one's all balance"
> IS-615: Full stake bug fix

- iconservice/iiss/engine.py
- tests/integrate_test/iiss/prevote/test_iiss_claim.py
> IS-605: rename feild in response 

- iconservice/prep/engine.py
- iconservice/prep/validator.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
- tests/integrate_test/iiss/decentralized/test_decentralization.py
- tests/integrate_test/iiss/decentralized/test_preps.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/prep/test_prep_data_validator.py
Modify validating regex and add tests for validating uri
* The international domain name is not supported
* To use idn, enter the punycode encoded value of idn
> Is-608: validate register p rep parameter

- iconservice/base/type_converter_templates.py
- iconservice/prep/data/prep.py
- iconservice/prep/engine.py
- iconservice/prep/validator.py
- tests/base/test_type_converter_iiss.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/prep/test_prep.py
- tests/prep/test_prep_container.py
* Fix PRep.Index.P2P_END_POINT
* Fix p2p_end_point in PRep
* Fix ConstantKeys.P2P_END_POINT
* Replace "p2pEndPoint" with "p2pEndpoint"
> IS-622: Replace end_point with endpoint

- iconservice/fee/engine.py
- tests/integrate_test/test_integrate_fee_sharing.py
Before IISS_REV: charge a fee to event log related with fee 2.0 
After IISS_REV: do not charge a fee to event log related with fee 2.0
> IS-592: Set revision about event log fee

- iconservice/prep/term.py
- tests/prep/test_term.py
* modify `save method` to store `current_block+1` to `_start_block_height` attribute
> IS-631: Fix save term bug

- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/prep/data/prep_container.py
- tests/integrate_test/iiss/decentralized/test_preps.py
- tests/integrate_test/iiss/test_iiss_base.py
* Apply low productivity penalty
> Is-629: add penalty logic

- iconservice/icx/icx_account.py
- iconservice/icx/storage.py
- iconservice/iiss/engine.py
- tests/icx/test_icx_account.py
- tests/integrate_test/iiss/prevote/test_iiss_stake.py
add prevalidator about preventing negative voting power
> IS-644: Fix occur negative voting power

- iconservice/base/type_converter_templates.py
- iconservice/prep/validator.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/prep/test_prep_data_validator.py
* Add Keys to template for registerPrep
* Enable input `localhost` to website, endpoint
> IS-643: Modify validating prep input data

- iconservice/prep/data/prep.py
- iconservice/prep/validator.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/prep/test_prep_data_validator.py
* Add _validate_country() to validator.py
* Add _validate_ctounry() unittest
> IS-651: country code validation

- iconservice/prep/engine.py
- tests/prep/test_engine.py
* Fix a bug in PRepEngine._update_prep_grades()
* Add prep/test_engine.py
> IS-650: bugfix update_prep_grades

- iconservice/icon_service_engine.py
- tests/integrate_test/iiss/prevote/test_prevote.py
> IS-660: Fix bug getIISSinfo

- iconservice/icon_service.py
* Change the timing of a current event loop setting in IconService class
> IS-620-bugfix-reward-calc-timeout

- iconservice/__init__.py
- iconservice/deploy/engine.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_base2.py
- iconservice/iconscore/icon_score_engine.py
- iconservice/iconscore/icon_system_score_base.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/decentralized/test_preps.py
- tests/prep/test_prep_container.py
- tests/test_icon_score_api.py
- tests/test_icon_score_deploy_engine.py
- tests/test_icon_score_engine.py
Add functions for network proposal
- get_main_prep_info()
- get_sub_prep_info()
- IconSystemScoreBase.unregister_prep()
Modify SCORE blacklist function
- SCORE blacklist blocks calling of SCORE external function
- SCORE blacklist does not block updating of SCORE
> Is 598 support network proposal

- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/icx/issue/engine.py
- iconservice/icx/issue/issue_formula.py
- iconservice/iiss/__init__.py
- iconservice/inner_call/__init__.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- tests/prep/test_engine.py
- tests/prep/test_term.py
- PREP_MAIN_PREPS : configure with 'mainPRepCount' key
- PREP_MAIN_AND_SUB_PREPS: configure with 'mainAndSubPRepCount' key
> IS-663: make PREP_MAIN_PREPS and PREP_MAIN_AND_SUB_PREPS configurable

- iconservice/icon_constant.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/test_iiss_base.py
* getXXXPRepList -> getXXXPReps
> Rename some APIs

- iconservice/prep/data/prep.py
- tests/integrate_test/iiss/prevote/test_prep.py
Add irep, irepUpdateBlockHeight fields to getPReps API
> IS-664: Add irep, irepUpdateBlockHeight fields to getPReps API

- iconservice/icon_service_engine.py
- iconservice/iiss/__init__.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- tests/prep/test_engine.py
- tests/prep/test_prep_container.py
* get_by_address() returns a P-Rep regardless of its status
* Replace __len__() with size()
* Remove get_inactive_prep_by_address()
* add() -> register()
* remove() -> unregister()
* Add add(), remove() and replace()
> IS-669: Improve PRepContainer

- iconservice/base/block.py
- iconservice/icon_service_engine.py
- iconservice/icx/storage.py
- iconservice/precommit_data_manager.py
* Fix context.block access error before genesis block is synchronized.
> IS-682: Fix context.block access error

- iconservice/prep/engine.py
- iconservice/utils/hashing/hash_generator.py
- iconservice/utils/hashing/merkle_tree.py
get merkle tree method from loopchain.
fix rep root hash generator
> IS-689: Fix rep root hash generator

- iconservice/base/type_converter.py
- iconservice/icon_constant.py
> IS-697: remove hash 0x

- iconservice/iconscore/icon_score_base2.py
- To support for Network Proposal of Governance
> IS-717: Add 'name' attribute on PRepInfo

- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/message_queue.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- tests/integrate_test/iiss/prevote/test_iiss_claim.py
* Implement CommitClaimRequest
* Add IISS_LOG_TAG
> IS-718: Add CommitClaim request

- iconservice/database/batch.py
- iconservice/database/db.py
- iconservice/iconscore/icon_container_db.py
- iconservice/meta/storage.py
- tests/database/test_db_batch.py
- tests/database/test_db_db.py
Before: value
After: (value, include_root_hash)
> IS-733:  Change the data structure of tx batch's value

- iconservice/deploy/engine.py
add icon score mapper tx batch on deploy
> IS-441: add icon score mapper tx batch on deploy

- iconservice/iconscore/icon_score_context.py
- iconservice/prep/engine.py
arrange get prep by address to get prep in context
> IS-741: Arrange get PRep

- iconservice/database/db.py
- iconservice/meta/storage.py
- tests/database/test_db_db.py
- tests/mock_generator.py
Define new class: MetaContextDatabase
this class only used in meta storage
> IS-746: Restrict setting include_root_hash

- iconservice/iiss/engine.py
add comment that why I don't changed it.
> IS-758: add comment in set_gv_method

- iconservice/iconscore/icon_system_score_base.py
It should be pulled with a related pull request of governance at the same time whose link is as below.
icon-project/governance#21
> IS-757: Modify method name from unregister prep to disqualify prep

- iconservice/iconscore/icon_score_event_log.py
- iconservice/prep/engine.py
- Fix argument type from enum to int
> IS-764: Raise exception when event log data is invalid

- iconservice/database/batch.py
- iconservice/database/db.py
- iconservice/iiss/reward_calc/storage.py
- tests/database/test_db_batch.py
- tests/database/test_db_db.py
- tests/database/test_transaction_batch.py
- tests/iiss/mock_rc_db.py
- tests/iiss/test_reward_calc_data_storage.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
- tests/mock_generator.py
> Fix the block about block batch

- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
Increase IPC timeout from 1 sec to 5 sec if RCP does not get RC READY message
> IS-778: Modify IPC timeout

- iconservice/icon_service_engine.py
- iconservice/icx/issue/regulator.py
- iconservice/iiss/engine.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
- tests/integrate_test/test_integrate_base.py
Checkpoint:
1. callback function (calculate_callback) is called 
2. regulate the difference between IS - RC
Handling:
if block height is invalid, raise Fatal exception
> IS-774: Check the block height of calculate response when regulating

- iconservice/icon_constant.py
- iconservice/iiss/engine.py
- tests/integrate_test/iiss/prevote/test_iiss_stake.py
- tests/integrate_test/iiss/test_iiss_base.py
Add estimateUnstakingPeriod JSONRPC method
> IS-768: Add estimateUnstakeLockPeriod JSONRPC method

- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/decentralized/test_decentralized2.py
- tests/integrate_test/iiss/test_iiss_base.py
fix bug next term block height on get_iiss_info()
re implement last calc, term infos in meta storage
== change period scenario ==
before deserialize period : calc period (43200)
after deserialize period: term period (43120)
> IS-779: Change calc_period to term_period on decentralization

- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/data_creator.py
- iconservice/iiss/reward_calc/msg_data.py
- tests/iiss/test_iiss_data_using_level_db.py
- tests/iiss/test_reward_calc_data_storage.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
Give information about main, sub prep count to the reward calculator
> IS-777: Give information about main, sub prep count to the reward calculator

- iconservice/iiss/reward_calc/ipc/message_queue.py
- tests/iiss/ipc/test_message_unpacker.py
Modify test case by adding changed message classes
* Test whether unpacker can unpack edited messages (Calculate, CommitClaim, Ready, CalculateDone)
> IS-784 : Enhance rewardcalcproxy test

- iconservice/icon_constant.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/decentralized/test_preps.py
- tests/integrate_test/iiss/test_iiss_base.py
Add getP2PEndpoints JSON-RPC-API
> IS-791: Add getP2PEndpoints JSON RPC API

- iconservice/base/exception.py
- iconservice/icon_constant.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/message_queue.py
- iconservice/iiss/reward_calc/ipc/message_unpacker.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
Add QUERY_CALCULATE_STATUS, QUERY_CALCULATE_RESULT messages
> IS-773 : synchronize icon service with reward calculator

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
Write IconScoreContextFactory
* make context using IconScoreContextFactory in invoke, query, estimate and commit methods.
> IS-785: Implement IconScoreContextFactory

- iconservice/iiss/reward_calc/ipc/server.py
Add log when send request to RewardCalc or receive response from RewardCalc
> IS-810 : Add log between iconservice rc communication

- iconservice/icon_service_engine.py
- iconservice/precommit_data_manager.py
> Add precommit data logging

- iconservice/icx/issue/engine.py
- iconservice/icx/issue/issue_formula.py
- iconservice/icx/issue/regulator.py
All log's level is 'INFO' temporarily
> IS-731: Supplement log about issuing

- iconservice/base/type_converter.py
- iconservice/base/type_converter_templates.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/data_creator.py
- iconservice/meta/storage.py
- iconservice/prep/engine.py
- tests/base/test_type_converter.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
- tests/integrate_test/iiss/decentralized/test_preps_replace_in_term.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/integrate_test/test_integrate_base.py
- tests/test_icon_inner_service.py
change block invoke protocol between LC and IS.
add prev_balock_votes field in block invoke parameter.
Fix integrate test about replace prep in term.
> IS-827: Previous validator management

- iconservice/base/type_converter_templates.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/data_creator.py
- tests/base/test_type_converter.py
- tests/integrate_test/iiss/decentralized/test_preps_replace_in_term.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/integrate_test/test_integrate_base.py
change type convert bool -> int
change type hint bool -> int
Fix tests
> IS-831: Previous validator management2

- iconservice/icx/issue/engine.py
- iconservice/icx/issue/issue_formula.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
Check main, sub preps total delegated when calculating beta2
> IS-775: Consider the case that main sub preps delegated amount is 0

- iconservice/prep/data/prep.py
* Update from_bytes() and to_bytes() on PRep to be compatible with MainNet
> Update PRep class for MainNet backward compatibility

- iconservice/iconscore/icon_system_score_base.py
- iconservice/prep/engine.py
- disqualify_prep() return tuple
- success : bool
- fail reason : str
> IS-850: add exception handling when disqualify P-Rep

- iconservice/iconscore/score_package_validator.py
- tests/integrate_test/samples/sample_deploy_scores/import_test/import_package/package.json
- tests/integrate_test/samples/sample_deploy_scores/import_test/import_package/sample_score.py
- tests/integrate_test/test_integrate_import_whitelist.py
add ICONSERVICE_WHITELIST class member variable.
add test case.
> IS-844: Improvement import validator

- iconservice/__init__.py
- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_score_base2.py
- iconservice/iconscore/icon_score_context.py
- iconservice/iconscore/icon_score_engine.py
convert score method to global method.
convert static method.
> IS-507: convert score method to global method

- iconservice/database/batch.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- iconservice/iiss/reward_calc/storage.py
- iconservice/prep/engine.py
- tests/iiss/test_reward_calc_data_storage.py
we are going to enable merging block_state_root_hash and RC-state-hash on every calculation block.
> IS-842: reflect rc root hash to is state root hash

- iconservice/prep/data/term.py
- tests/prep/test_term.py
* Set total_elected_prep_delegated in Term.from_list()
* Add __eq__()
* Update unittest for Term class
> Fix a bug in Term class

- iconservice/icon_inner_service.py
change log level in query and prevalidate.
change log form of response data to origin data in invoke.
> IS-848: improvement iconservice loggiing message.

- iconservice/icon_constant.py
- iconservice/iiss/engine.py
- do not send CLAIM message to RC for error claim TX
- error claim TX get 0 result
> IS-824: Skip error claim TX

- iconservice/iiss/reward_calc/ipc/message.py
* Add code that check bytes avail variable in toString whether it is bytes or not
* If node is Leader, BlockHash can be nil In claim or others. because of this, checked all of bytes avail variables.
> IS-864: QueryCalculateResult Timeout

- iconservice/database/db.py
- iconservice/icon_service_engine.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- iconservice/iiss/reward_calc/storage.py
Guarantee that 'standby_rc_db' is changed to 'iiss_rc_db' when recovering RC DB
Refactor _recover_rc_db method
> IS-863: Guarantee that standby rc db is changed to iiss rc db when recovering rc db

- iconservice/iiss/reward_calc/storage.py
- tests/iiss/test_reward_calc_data_storage.py
tests/iiss/test_reward_calc_data_storage.py
- test_commit_with_iiss_tx
- test_commit_without_iiss_tx
- test_rc_storage_check_data_format_by_revision
> IS-861: Fix some errors on unittest for RewardCalcStorage.commit()

- iconservice/iiss/engine.py
- tests/integrate_test/iiss/prevote/test_iiss_claim.py
- make eventLogs when claim 0 I-Score
> IS-871: Fix eventLogs of claim TX

- iconservice/icon_service_engine.py
- iconservice/iiss/reward_calc/storage.py
> Fix a bug on IconServiceEngine._recover_rc_db()

- iconservice/icon_service_engine.py
- iconservice/precommit_data_manager.py
- tests/integrate_test/iiss/decentralized/test_decentralized.py
- tests/integrate_test/test_integrate_base.py
add field in PrecommitData (added_transaction, main_preps)
> IS-887: Add invoke cache data

- iconservice/icon_service_engine.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
- tests/integrate_test/iiss/test_recover_using_wal.py
Bug report: In case of changing current db to standby db when recovering, the name of db was invalid (specifically block height), so fix this bug
If you want to check which case is considered, check the Jira issue
> IS-872: Implement tests of WAL

- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/storage.py
> add info log

- iconservice/icon_config.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
* Change default iconRcPath: "/usr/local/bin" -> ""
* Do not use "cwd" parameter in Popen()
> Refactor icon_rc command line

- iconservice/prep/penalty_imposer.py
- tests/prep/test_penalty_imposer.py
Change the order of condition when judging penalty on penalty imposer.
> IS-932: Impose low productivity penalty when prep get block validation and low productivity penalty at the same time

- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/message_unpacker.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- tests/iiss/ipc/test_message_unpacker.py
- tests/integrate_test/test_integrate_base.py
* Add tx_index and tx_hash to ClaimRequest and ClaimResponse
* Add block_hash field to ReadyNotification
> IS-942: Fix the state inconsistency for claimIScore TX between iconservice and rc

- iconservice/icon_constant.py
Add "getInactivePReps" on PREP_METHOD_TABLE
> IS-946: Bugfix getInactivePReps API 

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/storage.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
Change the time of putting the BP data of the start block of term 
before: Put on invoke
after: Put on commit
> IS-970: Fix the bug of writing invalid BP data on the start block of term 

- README.md
badges of ![Build Status](https://travis-ci.org/icon-project/icon-service.svg?branch=master) and ![PyPI](https://img.shields.io/pypi/v/iconservice)
> IS-975 : add badges of travis-ci and pypi

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/storage.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
Change the time of putting the BP data of the start block of term
before: Put on invoke
after: Put on commit
> IS-970: Fix the bug of writing invalid BP data on the start block of term

- iconservice/iconscore/icon_score_context.py
- iconservice/prep/engine.py
- iconservice/prep/prep_address_converter.py
- tests/integrate_test/iiss/decentralized/test_preps_divide_node_address.py
- tests/prep/test_prep_address_converter.py
* append update_prep_address_converter's logic on update_prep_batch of ICONScoreContext class
* reposition replace_function input parameters
* add integration test
> IS-1002: Consider fail Tx(included penalty) case

- iconservice/icx/engine.py
- iconservice/icx/storage.py
- tests/integrate_test/test_integrate_fee_sharing.py
- Can't withdraw deposit if penalty is charged
> IS-1042 fix Fee 2.0 bug

- iconservice/icon_service_engine.py
- system SCORE `inter-call` will be charged with CONNTRACK_CALL
> IS-1044 do not charge CONTRACT_CALL step to system SCORE call

- requirements.txt
* Update the versions of third-party packages in requirements.txt
> IS-1020: Update requirements.txt

- iconservice/iiss/engine.py
- iconservice/prep/engine.py
- tests/legacy_unittest/iiss/test_iiss_engine.py
- tests/legacy_unittest/prep/test_engine.py
- charge CONNTRACK_CALL step
- raise InvalidParamException
> IS-1052 add revision checking in IISS and P-Rep method

- .travis.yml
- setup.cfg
- setup.py
- remove setuptools test command deprecated (https://github.com/pypa/setuptools/issues/1684)
> IS-1054 : fix test fail of travis-ci

- iconservice/base/type_converter.py
- tests/integrate_test/iiss/prevote/test_iiss_claim.py
- tests/integrate_test/iiss/prevote/test_iiss_delegation.py
- tests/integrate_test/test_integrate_score_method_parameters.py
- tests/integrate_test/test_integrate_score_oninstall_parameters.py
- tests/integrate_test/test_integrate_score_onupdate_parameters.py
- tests/legacy_unittest/base/test_type_converter_func.py
- tests/legacy_unittest/test_icon_score_engine.py
- Add default value checking
- If all params are invalid, raise exception
> IS-1070 modify SCORE parameter checking

- iconservice/base/type_converter_templates.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- tests/integrate_test/iiss/2-depth/test_2depth_invoke_change_block_hash.py
- tests/integrate_test/iiss/2-depth/test_integrate_sending_icx_using_fee.py
- tests/integrate_test/iiss/test_change_block_hash.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_icon_service_engine.py
- tests/legacy_unittest/test_icon_inner_service.py
- tests/unittest/base/test_type_converter.py
connection innerservice "change_block_hash"
* add typeconvert for change block hash
* add cache blockhash to instantblockhash for leader
> IS-1085: Implement Change Block Hash

- iconservice/database/db.py
- iconservice/iconscore/icon_container_db.py
- iconservice/iconscore/icon_score_mapper_object.py
* cache size (before load size value everytime)
* remove Governance SCORE cache instance
> IS-1014: cache size field in array db

- iconservice/iconscore/icon_pre_validator.py
- iconservice/icx/storage.py
- tests/legacy_unittest/icon_score/test_icon_pre_validator.py
* Add address to "Out of balance" message in IconPreValidator
* Record a log when there is no account info for a given address
* Fix a minor bug in unittest
> IS-1100: Add log messages for "Out of balance" issue monitoring

- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service.py
- iconservice/icon_service_cli.py
- iconservice/icon_service_engine.py
- setup.py
- tests/unittest/iconservice.json
- tests/unittest/test_icon_config.py
* If config keys are not valid, log them with info level and keep running
* If config value types are not valid, log them with error level and stop running
* Implement ConfigSanityChecker
* Add unittests
> IS-1092: Configuration sanity check

- iconservice/prep/engine.py
Fix SetPRep Backword compatibillity
> IS-1157: Backward compatibility for node address division

- iconservice/iconscore/system_score.py
- iconservice/iiss/engine.py
- tests/integrate_test/test_integrate_get_score_api.py
- tests/integrate_test/test_integrate_system_score_internal_call.py
- claim I-Score with SCORE account
- add event log `IScoreClaimedV2(Address,int,int)`
> IS-1169: fix bug in claimIScore via SCORE inter-call

- .travis.yml
- deploy test pypi on release branch by tagging
- deploy pypi on master branch by tagging
> [IS-1170] update travis pypi deploy

- .travis.yml
- add regex to trigging when match tags
- fix slack notification secure
> [IS-1170] fix to deploy when tag push

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/prep/penalty_imposer.py
- iconservice/prep/prep_address_converter.py
- tests/integrate_test/iiss/decentralized/test_preps_divide_node_address.py
- tests/legacy_unittest/prep/test_prep_address_converter.py
Fix PRepCOnverter Delete Logic
append log
> IS-1174: Fix PRepConverter Delete Logic

- docs/api-references/classes.interfacescore.md
- iconservice/iconscore/icon_score_base2.py
- iconservice/iconscore/icx.py
* Add "icx(value: int)" document
* Related to iconservice API references made by sphinx
> IS-1179: Update InterfaceScore document

- iconservice/iconscore/icon_pre_validator.py
- tests/unit_test/iconscore/test_icon_pre_validator.py
* Fix db sync error at BH-434382
> IS-1217: Minor update to address locking

- Makefile
It can be run test, wheel build, etc. with `make`
```
test     Run pytest
clean    Clean all - clean-build
build    Build python wheel
```
> [IS-1180] add Makefile

- iconservice/icon_service.py
- requirements.txt
Package update
earlgrey 0.1.0 -> 0.1.1
> IS-1222: Apply earlgrey 0.1.1

- iconservice/__version__.py
Reverts icon-project/icon-service#535
> Revert "VERSION: 1.8.0rc2"

- iconservice/iconscore/db.py
Reverts icon-project/icon-service#533
> Revert "IS-1291: db observer missing"

- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/message_unpacker.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- iconservice/utils/__init__.py
- iconservice/utils/test_env.py
- tests/conftest.py
- tests/legacy_unittest/iiss/ipc/test_message_unpacker.py
* Send START_BLOCK message to reward calculator before invoking a block
* Tested with icondbtools and a new reward calculator
> IS-1321: Add START_BLOCK message for reward calculator

- iconservice/icon_service_engine.py
* Add a log for measuring tx processing time
> IS-1334: Measure tx processing time
