- iconservice/iconscore/score_package_validator.py
add function to be noticed by the import system like SCORE loader class.
if not, it is broken out error which no module in unittest (#3)
> if enable SCORE package validator,

- iconservice/deploy/icon_score_deploy_engine.py
- iconservice/deploy/icon_score_deploy_storage.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_score_context.py
- iconservice/iconscore/icon_score_context_util.py
- iconservice/iconscore/icon_score_engine.py
- iconservice/iconscore/icon_score_mapper.py
- iconservice/iconscore/icon_score_mapper_object.py
- iconservice/iconscore/icon_system_score_base.py
- iconservice/iconscore/internal_call.py
- tests/icon_score/test_external_payable_call_method.py
- tests/integrate_test/test_integrate_deploy_audit_install.py
- tests/integrate_test/test_samples/test_builtin/0_0_5/governance/__init__.py
- tests/integrate_test/test_samples/test_builtin/0_0_5/governance/governance.py
- tests/integrate_test/test_samples/test_builtin/0_0_5/governance/package.json
- tests/integrate_test/test_samples/test_builtin/latest_version/governance/governance.py
- tests/test_icon_score_engine.py
- tests/test_icon_score_event.py
- tests/test_icon_score_loader.py
- tests/test_icon_service_engine.py
- tests/test_icon_zip_deploy.py
currently IconScoreContext class is constituted data_struct and link system SCORE API (#8)
so someone who develop SCORE can accept API function which can't use
therefore I try to refactoring code about IconScoreContext Class
TODO. Divide that class to data class and API class
IconScoreContext : Contains the useful information to process user's jsonrpc request like invoke and query, and have tools which can access governance api
prev)
IconScoreContext <- data struct + API
after)
IconContext <- data struct
IconContextUtil <- API
IconContextUtil only have static method for using context API
> Divide IconScoreContext class

- iconservice/deploy/icon_score_deploy_engine.py
- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_deploy_whitelist.py
- tests/integrate_test/test_integrate_existent_scores.py
- tests/integrate_test/test_integrate_existent_scores_audit.py
- tests/integrate_test/test_integrate_service_configuration_initial.py
- tests/test_icon_service_engine.py
When open the icon service engine(open()), receives the config information(JSON format) and proceed config setting. When setting service config, inconsistency between camel case config name and the constant config name occurs(e.g. deployerWhiteList != DEPLOYER_WHITE_LIST), so config cannot be set properly. So solved the problem and added a unit test.
> Fix the bug that has caused when changing constant names

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_engine.py
- tests/test_icon_score_engine.py
- tests/test_icon_score_result.py
- tests/test_icon_score_step.py
- tests/test_icon_score_trace.py
1. Remove __icx_storage and __icon_score_mapper because of not being used anymore.
2. Make all icon score engine's functions as static. Detach Icon score engine from icon service engine. 
3. Modify unit tests which had been failed after refactoring icon_score_engine.
> Icon score engine refactoring

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- tests/database/test_db_db.py
- tests/icon_score/test_external_payable_call_method.py
- tests/icon_score/test_icon_container_db.py
- tests/icx/test_icx_engine.py
- tests/icx/test_icx_storage.py
- tests/test_icon_score_context.py
- tests/test_icon_score_deploy_engine.py
- tests/test_icon_score_engine.py
- tests/test_icon_score_loader.py
- tests/test_icon_service_engine.py
- tests/test_icon_zip_deploy.py
1. Create IconScoreContext using its constructor rather than IconScoreContextFactory.create method
2. Remove IconScoreContextFactory
3. Modify context related unittests
> Remove iconscorecontextfactory

- iconservice/iconscore/icon_score_mapper.py
- tests/integrate_test/test_integrate_builtin_governance.py
SCORE_PACKAGE_VALIDATOR flag must enable only specific governance SCORE version afterward.
so I add default preset that situation.
> fix builtin governance, when activate score_package_validator flag

- iconservice/icon_service.py
I want to apply to add amqp_target in check_rabbitmq function.
because of we can't do when we want to connect external host like "1.1.1.1"
also we are going to fix rpcserver like this.
> fix bug in check_rabbitmq

- iconservice/iconscore/icx.py
- iconservice/iconscore/internal_call.py
I found db sync bug when I tried to sync testnetDB at 33,756 BH.
this bug is occur by internal_call codes.
I fixed that none -> "fallback" already. but about "fallback" I can't edit SCORE db's info.
but multisigwallet SCORE already saved some tx's info to call this SCORE external function before. 
even transfer icx. so I fixed like this.
> fix internal_call_refactoring

- iconservice/iconscore/icon_score_api_generator.py
- iconservice/iconscore/icon_score_base.py
we don't need to execute IconScoreBaseMeta's logic in systemSCORE
so I add filtering check logic for skip below logics
and
I add raise exception code to prevent keyword argument on deploy function like on_install and on_update
> remove unused logic about system_score_base

- iconservice/iconscore/icon_score_api_generator.py
add revision branch code using context
> "Keyword arguments not allowed" exception causes MainNet db sync test to be failed.

- iconservice/utils/__init__.py
- tests/test_utils.py
Fix the representation of bytes for negative numbers located in edge such as 0x80, 0x8000, ... .
- negative numbers located in edge such as -128, -32768 are stored as 0x80, 0x8000
- positive numbers such as 128, 32768 are stored as 0x0080, 0x008000
> IS-356: Fix the representation of bytes for int

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_pre_validator.py
- iconservice/iconscore/icon_score_step.py
- tests/base/test_type_converter.py
- tests/base/test_type_converter_func.py
- tests/icon_score/test_icon_pre_validator.py
- tests/integrate_test/test_integrate_deploy_install.py
- tests/integrate_test/test_integrate_estimate_step.py
- tests/test_icon_score_step.py
- basic rule
- Calculating strings
: Counts UTF-8 encoded byte length
~- Calculating binaries (0x prefixed lowercase hex-string)~
~: Counts real byte length~
~- 0x prefixed hex-string which included uppercases is not a binary~
- when pre-validating
- Counts key and value as a string
- Reject non-binary data on message type transaction
- when input STEP counting
- Counts key and value
- Counts key as a string
~- If the value is 0x prefixed lowercase hex-string, counts as a binary~
~- If the value is a negative integer(e.g. -0x1a2b3c), counts as a binary with removing a sign.~
~- Otherwise, counts as a string~
- Counts value as a string
- when content(deploying) STEP counting
- Calculating as a binary
> IS-270: Improve input data calculating rule

- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_score_mapper_object.py
- tests/integrate_test/test_integrate_existent_scores.py
- tests/integrate_test/test_integrate_existent_scores_audit.py
- tests/integrate_test/test_integrate_fallback_call.py
- tests/integrate_test/test_integrate_member_variable_score.py
accoording to policy, change revision4 to revision3 about all logic
I think it should assign value explicitly .
remove default input param revision=3 in integration-test.
> IS-370: Unify revision3 and revision4 into revision3

- iconservice/iconscore/icon_pre_validator.py
- tests/icon_score/test_icon_pre_validator.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_deploy_install.py
- tests/integrate_test/test_integrate_score_method_parameters_type.py
- tests/integrate_test/test_integrate_service_configuration.py
Validates whether the leaf fields of transaction data are str or None on pre-validating
```json
{
...
"data": {
"method": "myMethod",
"params": { 
"a": 10000, 
"b": false, 
"d": 10.1 
}
}
...
}
```
> IS-377: Reject non-string values of input data field on pre-validating

- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- tests/test_icon_score_result.py
- tests/test_icon_score_step.py
Add missed ContextContainer._pop_context() call
Clear context stack in IconInnerService
Fix missed pop_context() bug in unittest
> IS-403: Fix memory leak for IconScoreContext

- iconservice/iconscore/icon_score_engine.py
- tests/integrate_test/test_integrate_estimate_step.py
- tests/test_icon_score_engine.py
1. Implement unit test about icon score engine.
2. Modify '_convert_score_params_by_annotations' method.
before: tmp_params get the reference of kw_params
after: tmp_params get the copied data of kw_params (no dependency with kw_params)
> IS-398: Add unit tests for IconScoreEngine

- iconservice/base/block.py
- iconservice/base/type_converter_templates.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_result.py
- iconservice/precommit_data_manager.py
- tests/base/test_type_converter.py
- tests/integrate_test/test_integrate_base.py
- tests/test_icon_inner_service.py
- tests/test_icon_score_result.py
- tests/test_icon_service_engine.py
1. Replace instant block hash with confirmed block hash on write_precommit_data
Consider backward compatibility.
2. Change commit and rollback method's parameter
as only hash data is needed, does not get Block obj as a parameter
3. Remove block hash in tx_result 
in invoking stage, block hash getting from loopchain is instant data (not real block hash). so remove this field from tx_result
> IS-494: Replace instant block hash with confirmed block hash

- docs/api-references/classes.iconscorebase.md
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_score_constant.py
- iconservice/iconscore/icon_score_engine.py
- iconservice/iconscore/internal_call.py
- tests/icon_score/test_external_payable_call_method.py
- tests/test_icon_score_class_loader.py
- tests/test_icon_score_engine.py
Prevent access to all internal functions except for officially provided SCORE APIs
in goveranace API cases, add worn.
update docs except for Fee2.0
> IS-402: prevent-access-score-functions-except-for-official

- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_system_score_base.py
- tests/test_icon_score_step.py
every time deploying and loading SCORE, it occurs warn log (get_owner, is_score_active).
so we fixed that issue.
> IS-402: Prevent access score functions except for official ones

- iconservice/base/exception.py
- iconservice/icon_inner_service.py
- iconservice/icon_service.py
- iconservice/icon_service_engine.py
- iconservice/icx/issue/engine.py
- iconservice/icx/issue_data_validator.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/storage.py
- tests/iiss/test_reward_calc_data_storage.py
- tests/integrate_test/test_integrate_issue_transaction_validation.py
1. Implement logic about getting I-SCORE from the reward calculator
2. Define new exception: InvalidBlockException
If this exception raise, return the error response implying the negative vote to loopchain.
3. After this implementation, raising an exception which inherits Exception (e.g. AssertionError) will be treated as a shutdown of icon service. (so close the icon inner service)
> IS-552: Get I SCORE being issued on the previous calculating period from the reward calculator

- iconservice/base/type_converter_templates.py
- iconservice/database/batch.py
- iconservice/icon_constant.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/inner_call/__init__.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- tests/integrate_test/prep/test_prep.py
- tests/integrate_test/test_integrate_base.py
- Checks end block height and update main and sub preps on Prep engine
- Adds check valid revision, REV_DECENTRALIZATION for updating main and sub preps on icon service engine
- Makes prep transaction result on invoke
- Adds PREP_ID constant on config
- Removes saving term logic on iiss engine
- Assigns to a variable, main preps and sub ones on Term class
- Adds integration-test for checking term and updating preps
- Adds PrepResultState enum class  
- Revises method name from check_end_block_height to check_term_end_block_height
- PrepRsultState is applied to prep engine
> IS-572: Check term and update main and sub preps

- iconservice/database/db.py
- iconservice/deploy/engine.py
- iconservice/deploy/icon_builtin_score_loader.py
- iconservice/icon_service_engine.py
- tests/database/test_db_db.py
- tests/database/test_db_observer.py
- tests/icon_score/test_icon_container_db.py
- tests/integrate_test/samples/sample_internal_call_scores/sample_link_score/sample_link_score.py
- tests/integrate_test/samples/sample_internal_call_scores/sample_score/sample_score.py
- tests/integrate_test/test_integrate_score_internal_call.py
* Check db ownership on writing to IconScoreDatabase
* Put GOVERNANCE_ADDRESS to context.current_address before loading builtin-scores.
* Put `SCORE_ADDRESS` to `current_address` when deploying SCORE
* Update writing-permission-related unit tests
> IS-556: Prevent accessing SCORE's DB from the other SCORE

- iconservice/icx/issue/engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/storage.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/data/sorted_list.py
- iconservice/prep/engine.py
- tests/integrate_test/__init__.py
- tests/integrate_test/iiss/test_iiss_delegation.py
- tests/integrate_test/prep/test_preps2.py
- tests/integrate_test/test_integrate_base.py
- tests/prep/data/test_prep_container.py
- tests/prep/data/test_sorted_list.py
* Add exception handling on SortedList.__setitem__()
* Remove duplicated codes from PRepContainer.get_by_index()
* Add total_prep_delegated property to PRepContainer
* Load inactive P-Reps on PRepContainer.load()
* Remove unused methods from PRepContainer (replace() and set_to_prep())
* Error handling for duplicated addresses in setDelegation request
* BugFix on self delegation in IISSEngine.handle_set_delegation()
* Fix PRepContainer.get_by_address() not to raise an exception but to return None
* Some integration tests remain failed
> IS-586: Bugfix on PRepContainer and IISSEngine

- iconservice/iiss/engine.py
- tests/integrate_test/iiss/test_iiss_stake.py
Do not display unstake and unstakeBlockHeight field when its value nonexistent.
> Is-588: do not display nonfield get stake

- iconservice/icon_constant.py
- iconservice/prep/data/prep.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- tests/integrate_test/prep/test_prep.py
- tests/prep/data/test_prep_container.py
* Fix PRepEngine.handle_get_prep() to return an inactive prep with a given address
* Add get_inactive_prep_by_address to PRepContainer
* Change the data type of prep.status (str -> int) in JSON-RPC API response
* Add unit tests
> IS-593 Bugfix PRepEngine.handle_get_prep()

- iconservice/base/exception.py
- iconservice/icon_inner_service.py
- iconservice/icon_service.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/iconscore/icon_score_context_util.py
- iconservice/icx/issue/regulator.py
- iconservice/iiss/engine.py
- iconservice/iiss/storage.py
- tests/icx/issue/test_issue_regulator.py
- tests/integrate_test/test_integrate_base_transaction_validation.py
- tests/test_icon_inner_service.py
This exception implies closing the icon service because  the fatal error has been raised
this exception is treated as below in inner task
- In case of FatalException having been raised on invoke thread, should close the icon service after sending an error response.
- In case of FatalException having been raised on query thread, should not close the icon service.
> IS-590: Define 'FatalException' exception which implies close the icon service

- iconservice/utils/hashing/hash_generator.py
- tests/hashing/test_hash_generator.py
> IS-623: Remove '0x' when generating base transaction transaction hash

- iconservice/base/type_converter_templates.py
- iconservice/icon_constant.py
- iconservice/prep/data/prep.py
- iconservice/prep/engine.py
- requirements.txt
- tests/integrate_test/iiss/decentralized/test_preps.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/prep/test_prep.py
- tests/prep/test_prep_container.py
* Add grade, country and city attributes to PRep class
* Add iso3166 package to requirements.txt
* Update PRep.to_dict()
* Fix unittest failures
* Focused on getPRep and getPRepList JSON-RPC API only
* To add "stake" to PRep class is not included
> IS-626: Add new properties to PRep class

- iconservice/prep/data/prep.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/prevote/test_iiss_stake.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/prep/test_prep.py
* Add stake property to PRep class
* Add test_from_bytes_and_to_bytes to test_prep.py
* Add test_prep_stake to prevote/test_prep.py
* Rename start_index and end_index to start_ranking and end_ranking in unittest
> IS-637: PRep.stake management

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/prep/data/prep.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- tests/integrate_test/iiss/decentralized/test_decentralized.py
- tests/integrate_test/iiss/prevote/test_prevote.py
- tests/integrate_test/iiss/test_iiss_base.py
- tests/prep/test_term.py
1. Move 'is_decentralized' method from icon service engine to icon score context
Reason: this method could be used in many engines
2. Set term's irep to 0 when revision IISS_REV
3. Define '_initial_irep' member variable in prep engine
This variable is used when registering prep in revision IISS_REV. after decentralized, use term.irep (i.e. _initial_irep is only used when revision IISS_REV).
4. When weighted_average_of_irep is 0, return IISS_MIN_IREP.
> IS-642: Do not calculate i score for block producers until decentralized

- iconservice/icon_service_engine.py
- iconservice/inner_call/__init__.py
- iconservice/precommit_data_manager.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- tests/prep/test_term.py
* Update PRep.grade every term in PRepEngine.on_term_ended()
* Update the next_term in PRepEngine.commit()
* Unify main_preps and sub_preps into preps in Term class
* Add term field to PrecommitData class
* Move term-related logic to PRepEngine
* Split Term.save() into Term.update() and Term.save()
* Update some unittests
> IS-638: PRep.grade management

- iconservice/inner_call/__init__.py
- tests/integrate_test/iiss/test_inner_call.py
- tests/integrate_test/test_integrate_base.py
* modify the wrong argument
* add tests for innerCall
> IS-668: Fix API that raises error due to `get_main_preps_in_dict` method changed

- iconservice/icx/storage.py
Bug fix: change the order of putting data when genesis invoke and make treasury address being recorded
> IS-676: Match the order of putting the genesis invoke data and record treasury account on db

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/icx/base_part.py
- iconservice/icx/coin_part.py
- iconservice/icx/issue/engine.py
- iconservice/iiss/engine.py
- iconservice/prep/data/prep.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- iconservice/prep/term.py
- iconservice/utils/__init__.py
- tests/icx/test_coin_part.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
- tests/integrate_test/iiss/decentralized/test_preps.py
- tests/prep/test_engine.py
- tests/prep/test_prep_container.py
* Add context.tx_dirty_preps ordered dict
* Add get_prep() and put_dirty_prep() to IconScoreContext
* Apply context.tx_dirty_preps to registerPRep, unregisterPRep, setPRep,
setGovernanceVariables transactions
* Apply context.tx_dirty_preps to update_low_producivity, update_last_generate_block_height, update_block_statistics
* Apply context.tx_dirty_preps to on_set_stake, on_set_delegation
* Clean up deprecated method in PRepContainer
* PRepContainer.total_prep_delegated -> total_delegated
> IS-672: Fix missed P-Rep attributes recording

- iconservice/icon_service_engine.py
- iconservice/icx/issue/regulator.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/storage.py
- iconservice/meta/storage.py
- tests/icx/issue/test_issue_regulator.py
- tests/iiss/test_reward_calc_data_storage.py
- tests/integrate_test/iiss/prevote/test_prevote.py
1. Improve get_iiss_info API
2. Record block height when getting a response from RC about 'calculate'.
> IS-688: add API which returns the previous calc period total i score

- iconservice/icon_service_engine.py
If low productivity penalty is already imposed on a P-Rep,
sequence block validation failure penalty should be ignored.
> IS-756: Arranged impose penalty by priority

- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/prep/data/prep.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/decentralized/test_preps_replace_in_term.py
PRep constant variables:
penalty_grace_period,
min_productivity_percentage,
max_unvalidated_sequence_blocks
we should change those constant variables by using icon-config
but I don't save these variables to DB yet because we don't need to change it dynamically.
> IS-755: setting prep config from icon-config

- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/data_creator.py
- iconservice/iiss/reward_calc/msg_data.py
- iconservice/iiss/reward_calc/storage.py
- tests/iiss/test_iiss_data_using_level_db.py
- tests/iiss/test_reward_calc_data_storage.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
1. Add revision field to header data of RC DB
2. Add version field to governance variable of RC DB
3. Define version and revision on reward calc storage
These variables are recorded on current RC DB. all data in this DB will be formatted according to this version information.
> IS-786: Add revision field to header data of RC DB 

- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
* The RewardCalculatorProxy has ready_future, so when ready comes, it sets the ready_future's set_result to True
* Waiting for RCProxy's ready_future in hello in icon_inner_service, then exit hello when it returns.
> IS-773 : Syncronize iconservice with reward Calculator

- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/icx/issue/regulator.py
- iconservice/icx/issue/storage.py
- iconservice/iiss/engine.py
- tests/icx/issue/test_issue_regulator.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
1. Implement get_prev_iscore method on iiss engine.
this method check and return the iscore (from RC)
2. Fix the unit tests
As the logic has been changed, the unit test also has been changed. The point is making logic no difference in the first calculate period. (i.e. do not check the prev_calc_issued_icx == -1)
> IS-801: Improve calculate related communication between IS and RC

- iconservice/icon_constant.py
- iconservice/icx/issue/regulator.py
- iconservice/iiss/engine.py
- tests/icx/issue/test_issue_regulator.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
Implement get_prev_iscore method on iiss engine.
this method check and return the iscore (from RC)
Fix the unit tests
As the logic has been changed, the unit test also has been changed. The point is making logic no difference in the first calculate period. (i.e. do not check the prev_calc_issued_icx == -1)
> IS-801: Improve calculate communication between iconservice and reward calculator

- iconservice/icon_constant.py
- iconservice/icx/issue/regulator.py
- iconservice/iiss/engine.py
- tests/icx/issue/test_issue_regulator.py
- tests/integrate_test/iiss/decentralized/test_base_transaction_validation.py
Distinguish the first term when regulating the issue amount
Implement get_prev_iscore method on iiss engine.
this method check and return the iscore (from RC)
Fix the unit tests
As the logic has been changed, the unit test also has been changed. The point is making logic no difference in the first calculate period. (i.e. do not check the prev_calc_issued_icx == -1)
Repeat querying calculate result when being received 'IN PROGRESS' from the RC
> IS-801: Improve calculate related communication

- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/message_queue.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- iconservice/iiss/reward_calc/ipc/server.py
- tests/integrate_test/iiss/prevote/test_iiss_claim.py
- tests/integrate_test/iiss/test_iiss_base.py
* Invalid address of queryIScore causes RewardCalcProxy._on_send() to crash
* Add address format sanity check for queryIScore
* Catch exceptions in Server._on_send() to keep ipc sender alive
* Catch exceptions in Server._on_recv() to keep ipc receiver alive
* Add task_done() to MessageQueue
* Add an unittest for queryIScore with invalid params
> IS-914: bugfix query_iscore

- iconservice/icon_inner_service.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- iconservice/iiss/reward_calc/ipc/server.py
- tests/iiss/ipc/test_message.py
* Put NoneRequest to MessageQueue to stop on_send() and on_recv()
* Fix some asyncio errors
* Clean up unused codes from IPCServer
* Fix a minor unittest error
* Update asyncio statements in IconInnerService
> IS-915: Fix infinite loop on ipc_server termination

- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/decentralized/test_in_term_prep_replacement.py
- tests/prep/test_engine.py
- Add get_inactive_preps on PrepContainer to return inactive P-Rep list sorted by penalty value and delegated amount
> IS-923: Add P-Rep candidates to the result of getPRepTerm API

- iconservice/prep/data/prep_container.py
- iconservice/prep/engine.py
- tests/prep/test_engine.py
- Add get_inactive_preps method on PrepContainer
- Add tests for the API
> IS-931: Implement get inactive p reps api

- iconservice/prep/engine.py
- tests/prep/test_engine.py
* Change the target prep list to reset the block validation penalty from engine.preps to context.preps
* Change the condition to pick up the P-Reps to reset the block validation penalty
* Rename PRepEngine._release_block_validation_penalty() to RepEngine._reset_block_validation_penalty()
* Add a unittest to prep/test_engine.py
> IS-929: Fix a bug on PRepEngine._reset_block_validation_penalty

- iconservice/iconscore/icon_score_engine.py
- tests/integrate_test/samples/sample_scores/sample_global_variable_score/global_variable_score.py
- tests/integrate_test/samples/sample_scores/sample_global_variable_score/package.json
- tests/integrate_test/test_integrate_global_variable_score.py
* Deepcopy the return value of score query call to prevent score data corruption
* Add a unittest for global score data corruption
> IS-936: Fix score data corruption on score query call

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/precommit_data_manager.py
- iconservice/prep/data/prep_container.py
- iconservice/prep/data/term.py
- tests/icon_score/test_icon_score_context.py
- tests/integrate_test/iiss/decentralized/test_rc_db_data.py
- tests/prep/test_term.py
- tests/utils.py
* Duplicate context.term only when it is needed to modify context.term on invoke process.
* Fix a bug that does not reset the flags when calling PRepContainer.freeze()
* Add some unittests
> IS-854: Optimize context.term duplication

- iconservice/prep/engine.py
Incase of reopening icon-service, the prep engine's term remains unfrozen. If the prep list is changed before the end of the period on which icon-service has been opened, the changed prep list is reflected directly in the prep engine's term. So fix this bugs
> IS-977: Fix the bugs that prep term remains unfrozen when open the icon-service

- iconservice/prep/engine.py
- tests/icon_score/test_icon_score_context.py
- tests/test_icon_score_deployer.py
* Freeze loaded term on rollback
* Check if term object is valid before calling Term.freeze()
* Fix package import error with a wrong relative path
* Comment out a assertion line of which result is different between MacOS and Linux
> IS-978: Fix minor unittest errors

- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/iiss/engine.py
- iconservice/prep/prep_address_converter.py
- tests/prep/test_prep_address_converter.py
* Remove node_address_to_prep_address()
* Remove is_contains_node_address()
* Remove '_' from  _get_prep_address_from_node_address()
* Refactor IconServiceEngine._get_prev_block_votes()
* Add an unittest for PRepAddressConverter
> IS-997: Refactor PRepAddressConverter

- iconservice/icon_service_engine.py
- iconservice/meta/storage.py
- iconservice/prep/engine.py
- iconservice/prep/prep_address_converter.py
- tests/icon_score/test_icon_score_context.py
- tests/prep/test_engine.py
- tests/prep/test_prep_address_converter.py
- tests/test_fee_sharing.py
- tests/test_icon_score_api.py
- tests/test_icon_score_result.py
- tests/test_icon_score_step.py
* Remove save(), load() and rollback()
* Fix errors in unittests
* Refactor get_prep_address_converter() and put_prep_address_converter() on meta storage
> IS-998: Refactor PRepAddressConverter2

- docs/api-references/classes.iconscorebase.md
- docs/api-references/classes.interfacescore.md
- docs/api-references/classes.md
- docs/api-references/index.md
- docs/dapp_guide.md
- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_score_base2.py
- tests/integrate_test/samples/sample_internal_call_scores/sample_link_score/sample_link_score.py
- tests/integrate_test/samples/sample_internal_call_scores/sample_score/sample_score.py
- tests/integrate_test/test_integrate_score_internal_call.py
- remove IconScoreBase.call() from deprecated API list
- there are 2 ways to transfer ICX
* self.call() method
set transfer amount with last parameter 'amount'
* self.create_score_interface() and @interface decorator
1. set transfer amount to 'value' member
- there are 2 ways
- assign int value with '=' operator
- ~~call set_transfer_value()~~
2. invoke @interface decorated method
> IS-982 SCORE intercall support ICX transfer

- iconservice/__init__.py
- iconservice/iconscore/icon_score_base2.py
- tests/test_icon_score_api.py
> IS-1024: Add sha_256 function for SCORE development

- iconservice/iconscore/icon_container_db.py
- tests/icon_score/test_icon_container_db.py
- tests/integrate_test/samples/sample_scores/sample_dict_db/package.json
- tests/integrate_test/samples/sample_scores/sample_dict_db/sample_dict_db.py
- tests/integrate_test/test_integrate_container_db_patch.py
officially we do not support iteration on DictDB
so add raise Exception code
references
https://www.python.org/dev/peps/pep-0234/
https://docs.python.org/3/reference/datamodel.html#object.__getitem__
> IS-1021: DictDB iteration causes infinite loop

- iconservice/icon_constant.py
- iconservice/icx/issue/engine.py
- tests/icx/issue/test_issue_engine.py
- tests/integrate_test/iiss/prevote/test_prep_registration_fee.py
I have checked other event signature which is made by system, and other signatures seem to no problem.  (I have Checked logic that use 'EventLogEmitter.emit_event_log' method)
> IS-1018: Fix ICX burned eventlog signature

- iconservice/database/db.py
- iconservice/iconscore/icon_container_db.py
- tests/integrate_test/test_integrate_container_db_patch.py
- tests/test_container_db.py
> IS-1029: Array Optimization hotfix

- iconservice/utils/msgpack_for_db.py
- iconservice/utils/msgpack_for_ipc.py
- requirements.txt
Modify arguments of msgpack.loads and msgpack.dumps due to default parameter changed in msgpack 1.0.0 release. And specify msgpack version to compatible with 1.0.x release.
> IS-1012: msgpack backward compatibility

- iconservice/icon_config.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
- tests/integrate_test/test_integrate_service_configuration_initial.py
Add configuration field: 'iconRcMonitor'
- Default: monitor on
I have tested this new feature and leave the logs in Jira
I have considered bundling up the RC configuration. below is example
`
"iconRc": {
"path": "",
"monitor": true
},
`
If above is more prefer way, I will modify the code accordingly.
> IS-991: Add option which determine opening RC monitor channel

- iconservice/iconscore/system_score.py
- tests/integrate_test/iiss/prevote/test_iiss_claim.py
- tests/integrate_test/iiss/prevote/test_iiss_delegation.py
- tests/integrate_test/iiss/prevote/test_iiss_stake.py
To get the same TX result with the master branch, removed payable decorator instead of adding check value logic. Below is the removed method list.
- setStake
- claimIScore
I have synced with this branch and it correctly worked.
You may worry about failure message format (as not the same with the master branch).
As a 'failure' message is not applied to block hash, it can be changed without revisioning.
> IS-1053: Transaction should be failed when calling claimIScore with value 

- iconservice/base/block.py
- iconservice/base/type_converter_templates.py
- iconservice/database/db.py
- iconservice/icon_inner_service.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/icx/storage.py
- iconservice/precommit_data_manager.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/2-depth/test_integrate_sending_icx_using_fee.py
- tests/integrate_test/iiss/change_block_hash.py
- tests/integrate_test/iiss/decentralized/test_decentralized2.py
- tests/integrate_test/iiss/decentralized/test_preps_divide_node_address.py
- tests/integrate_test/iiss/test_recover_using_wal.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_icon_service_engine.py
- tests/legacy_unittest/mock_generator.py
- tests/legacy_unittest/test_icon_inner_service.py
- tests/test_precommit_data_manager.py
- tests/unittest/base/test_type_converter.py
- tests/unittest/iiss/test_iiss_engine.py
* Mgr is managed like tree
* rename main_prep_as_dict to next_preps
* remove remove_precommit
* unittest fix
> IS-274: Refactoring Precommitdata Manager

- iconservice/iconscore/internal_call.py
- iconservice/iiss/engine.py
- iconservice/prep/engine.py
- tests/integrate_test/iiss/prevote/test_iiss.py
- tests/integrate_test/iiss/prevote/test_prep.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_system_score_internal_call.py
1. Drop TX calling IISS and P-Rep query (getStake, getPRep ...)
2. Allow Governance SCORE to call system SCORE inter-call before revision 9
> Fix stateDB synchronization failure due to system SCORE

- iconservice/base/block.py
- iconservice/database/batch.py
- iconservice/database/db.py
- iconservice/database/wal.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/icon_score_context.py
- iconservice/precommit_data_manager.py
- tests/__init__.py
- tests/integrate_test/test_integrate_base.py
- tests/integrate_test/test_integrate_existent_scores.py
- tests/integrate_test/test_integrate_existent_scores_audit.py
- tests/integrate_test/test_integrate_fee_sharing.py
- tests/legacy_unittest/database/test_db_batch.py
- tests/legacy_unittest/database/test_db_db.py
- tests/legacy_unittest/database/test_transaction_batch.py
- tests/unittest/test_precommit_data_manager.py
- format: JSON
- file path & file name: {LOG PATH}/precommit/{block height}-precommit-data-v{version num}.json
- Add tx_index field to TransactionBatchValue for debugging
-  There is some issue about retrieve index from the context in case of deploy (In deploy, context.tx is set to None temporally)
- Check assert when set items (i.e. __setitem__) on TransactionBatch (must be TransactionBatchValue)
- Only TransactionBatchValue type can be set on TransactionBatch
- I have left the comments on the major change point
```
{
"iconservice": "1.6.1",
"revision": 5,
"block": {
"height": 2,
"hash": "0xbf1ba1fcc5894f900a2424c7c23f5b4df52ddfa512aa6611554cffa63af3c885",
"timestamp": 1591318988717094,
"prevHash": "0x7833cedff6814fef8dc5f818d6307ef537e6d79087620629b73de8bf91caa283",
"cumulativeFee": …
```
> IS-1089: Write the log of precommit data to the seperated file

- iconservice/icon_service_engine.py
- iconservice/iiss/reward_calc/storage.py
- iconservice/rollback/rollback_manager.py
- os.rename() does not work if src, dst are in different filesystem
- https://docs.python.org/3/library/shutil.html#shutil.move
> IS-1131 change os.rename() to shutil.move()

- iconservice/__version__.py
- iconservice/prep/engine.py
- iconservice/prep/validator.py
- tests/integrate_test/iiss/decentralized/test_preps_divide_node_address.py
If engine received registerPRep, setPRep transaction before rev9, that logic filter params about nodeAddress For backword compatibility.
> IS-1157: Backword compatibility for divide Node key

- iconservice/icx/stake_part.py
- tests/legacy_unittest/icx/test_icx_account.py
- tests/legacy_unittest/icx/test_stake_part.py
Fix inserting unstake slot and refactor normalizing stakePart
* use linear search rather than wrong binary search to find index of new unstake slot
* use revision to divide logic in normalizing stakePart method
* if unstake slot if full and user add unstake, unstakeBlockHeight of last slot is max(unstakeInfo[-1][1], unstke_block_height)
> IS-1167: Fix inserting unstake slot and refactor normalizing stakePart

- iconservice/iiss/engine.py
- tests/integrate_test/iiss/prevote/test_iiss_stake.py
- tests/integrate_test/iiss/prevote/test_iiss_unstake_lock_period.py
Fix getStake API to response different format when IS revision8 and revision9
* response in previous format when revision is 8
* response in new format(has unstakesList) when revision is greater than 8
> IS-1166: Fix getStake API to response different format when IS revision8 and revision9

- iconservice/database/db.py
- iconservice/icon_constant.py
- iconservice/icon_service_engine.py
- iconservice/iconscore/db.py
- iconservice/iconscore/icon_container_db.py
- iconservice/iconscore/icon_score_base.py
- iconservice/iconscore/icon_score_context_util.py
- iconservice/iconscore/icon_score_result.py
- iconservice/utils/rlp.py
- tests/conftest.py
- tests/legacy_unittest/database/test_db_db.py
- tests/legacy_unittest/database/test_db_observer.py
- tests/legacy_unittest/test_icon_score_result.py
- tests/unit_test/iconscore/test_db.py
- tests/unit_test/iconscore/test_external_payable_call_method.py
- tests/unit_test/iconscore/test_icon_container_db.py
- tests/unit_test/iconscore/test_icon_score_trace.py
- tests/unit_test/iconscore/test_prefix_storage.py
- tools/precommit_converter/converter/converter.py
* Change final key generation mechanism
* Add unit-tests for ContainerDB and new IconScoreDatabase
* Clean up unused codes
> IS-1107: Refactor score database and container

- iconservice/iconscore/db.py
* Handle the special case when ContainerDBs are initialized before IconScoreBase.__init__() is called.
* The new implementation of IconScoreDatabase caused this problem.
> IS-1291: Fix the case that step is not charged for db writing

- iconservice/iiss/engine.py
- iconservice/iiss/reward_calc/ipc/message.py
- iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py
It takes too long when SCORE calls queryIScore intercall.
To fix this, the block height and block hash were added to the QUERY message.
Now RC does not iterate through preCommit DB when receiving QUERY message, it gets the element with key.
> Add block height and block hash to QUERY message

- requirements.txt
- fixed mismatch `typing-extensions` version with iconrpcserver requires
> [IS-1375] update typing-extensions requires
